# Generated by Django 5.2.8 on 2025-11-16 11:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Admin', 'Admin'), ('Storekeeper', 'Storekeeper'), ('Requester', 'Requester'), ('Auditor', 'Auditor')], max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField(default=uuid.uuid4)),
                ('action', models.CharField(max_length=32)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip', models.CharField(max_length=64)),
                ('user_agent', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('for_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(max_length=32)),
                ('min_stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('counted_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('delta', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('for_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.inventorycount')),
                ('for_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_count_lines', to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_no', models.CharField(max_length=64, unique=True)),
                ('dept_lab', models.CharField(choices=[('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Computer', 'Computer Science'), ('Engineering', 'Engineering'), ('Admin', 'Administration'), ('Other', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Fulfilled', 'Fulfilled')], default='Draft', max_length=16)),
                ('needed_by', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('for_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL)),
                ('for_requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('for_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('approved_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('issued_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('for_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisition_lines', to='core.item')),
                ('for_requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.requisition')),
                ('for_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisition_lines', to='core.stocklot')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Received', 'Received'), ('Closed', 'Closed')], default='Draft', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_wareho_name_c8ca8a_idx'), models.Index(fields=['is_active'], name='core_wareho_is_acti_1c4a79_idx')],
                'unique_together': {('name', 'location')},
            },
        ),
        migrations.AddField(
            model_name='stocklot',
            name='for_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='core.warehouse'),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('ADJUST', 'ADJUST'), ('RETURN', 'RETURN'), ('TRANSFER', 'TRANSFER')], max_length=16)),
                ('ref_type', models.CharField(choices=[('PO', 'PO'), ('REQ', 'REQ'), ('INVCOUNT', 'INVCOUNT'), ('OTHER', 'OTHER')], max_length=16)),
                ('ref_no', models.CharField(max_length=64)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('for_actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('for_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.item')),
                ('for_warehouse_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='core.warehouse')),
                ('for_warehouse_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='core.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='for_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='core.warehouse'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['code'], name='core_item_code_2c57e9_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active'], name='core_item_is_acti_8c2f25_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['for_category'], name='core_item_for_cat_b9f4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['type'], name='core_moveme_type_06fd12_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['for_item'], name='core_moveme_for_ite_359d30_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['for_warehouse_from'], name='core_moveme_for_war_fdd0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['for_warehouse_to'], name='core_moveme_for_war_2a62b7_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['created_at'], name='core_moveme_created_446d78_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['ref_type', 'ref_no'], name='core_moveme_ref_typ_e6aebc_idx'),
        ),
    ]
