/**
 * Language Context - مدیریت زبان و RTL
 */
import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'en' | 'fa';

interface LanguageContextType {
  language: Language;
  isRTL: boolean;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// ترجمه‌های ساده (می‌توانید بعداً به i18n تبدیل کنید)
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventory',
    'nav.requisitions': 'Requisitions',
    'nav.count': 'Count',
    'nav.reports': 'Reports',
    'nav.auditLog': 'Audit Log',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.logout': 'Log out',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back! Here\'s what\'s happening with your inventory today.',
    'dashboard.newRequisition': 'New Requisition',
    'dashboard.shortages': 'Shortages',
    'dashboard.pendingRequisitions': 'Pending Requisitions',
    'dashboard.activeCounts': 'Active Counts',
    'dashboard.totalItems': 'Total Items',
    'dashboard.lowStock': 'Low Stock Items',
    'dashboard.vsLastMonth': 'vs last month',
    'dashboard.reviewNow': 'Review Now',
    'dashboard.monthlyFlow': 'Monthly Flow',
    'dashboard.recentMovements': 'Recent Movements',
    'dashboard.lowStockAlert': 'Low Stock Alert',
    'dashboard.noShortages': 'No shortages detected',
    'dashboard.noPendingRequisitions': 'No pending requisitions',
    'dashboard.noActiveCounts': 'No active counts',
    'dashboard.noLowStock': 'All items are well stocked',
    'dashboard.noMovements': 'No recent movements',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.quickActionsDesc': 'Common tasks and shortcuts',
    'dashboard.createRequisition': 'Create Requisition',
    'dashboard.recordMovement': 'Record Movement',
    'dashboard.startCount': 'Start Inventory Count',
    'dashboard.viewReports': 'View Reports',
    'dashboard.stockTrends': 'Stock Trends',
    'dashboard.weeklyStock': 'Weekly stock level',
    'dashboard.noData': 'No data available',
    'dashboard.thisMonth': 'This Month',
    'dashboard.shortage': 'Shortage',
    'dashboard.critical': 'Critical',
    
    // Inventory Management
    'inventory.title': 'Inventory Management',
    'inventory.description': 'Manage items, warehouses, lots, and movements',
    'inventory.items': 'Items',
    'inventory.warehouses': 'Warehouses',
    'inventory.warehousesShort': 'WH',
    'inventory.lots': 'Lots / Batches',
    'inventory.lotsShort': 'Lots',
    'inventory.movements': 'Movements',
    
    // Requisitions
    'requisitions.title': 'Requisitions',
    'requisitions.new': 'New Requisition',
    'requisitions.create': 'Create Requisition',
    'requisitions.approve': 'Approve',
    'requisitions.reject': 'Reject',
    'requisitions.fulfill': 'Fulfill',
    'requisitions.status': 'Status',
    'requisitions.draft': 'Draft',
    'requisitions.pending': 'Pending',
    'requisitions.approved': 'Approved',
    'requisitions.rejected': 'Rejected',
    'requisitions.fulfilled': 'Fulfilled',
    
    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Change Language',
    'settings.currentLanguage': 'Current',
    'settings.switchToEnglish': 'Switch to English',
    'settings.switchToPersian': 'تبدیل به فارسی',
    'settings.security': 'Security Settings',
    'settings.securityDescription': 'Configure security policies and session settings',
    'settings.sessionTimeout': 'Session Timeout (minutes)',
    'settings.passwordPolicy': 'Password Policy',
    'settings.minChars': 'Minimum 8 characters',
    'settings.requireCase': 'Require uppercase and lowercase',
    'settings.requireNumbers': 'Require numbers',
    'settings.saveSecurity': 'Save Security Settings',
    
    // Login
    'login.title': 'Inventra',
    'login.subtitle': 'Inventory Tracking App',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.usernamePlaceholder': 'Enter your username',
    'login.passwordPlaceholder': 'Enter your password',
    'login.signIn': 'Sign In',
    'login.loading': 'Loading...',
    'login.mockMode': 'Use any username/password to login (Mock Mode)',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.actions': 'Actions',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.role': 'Role',
    'common.admin': 'Admin',
    'common.storekeeper': 'Storekeeper',
    'common.requester': 'Requester',
    'common.auditor': 'Auditor',
    'common.menu': 'Menu',
    'common.all': 'All',
    'common.select': 'Select',
    'common.view': 'View',
    'common.details': 'Details',
    'common.noData': 'No data found',
    'common.found': 'found',
    'common.items': 'items',
    'common.item': 'item',
    'common.warehouse': 'Warehouse',
    'common.allWarehouses': 'All Warehouses',
    'common.category': 'Category',
    'common.allCategories': 'All Categories',
    'common.startDate': 'Start Date',
    'common.endDate': 'End Date',
    'common.thisMonth': 'This Month',
    'common.neededBy': 'Needed by',
    'common.department': 'Department',
    'common.manage': 'Manage',
    'common.track': 'Track',
    'common.activity': 'Activity',
    'common.entity': 'Entity',
    'common.allEntities': 'All Entities',
    'common.allActions': 'All Actions',
    'common.currentStock': 'Current Stock',
    'common.minStock': 'Min Stock',
    'common.shortage': 'Shortage',
    'common.consumption': 'Consumption',
    'common.byDepartment': 'By Department',
    'common.address': 'Address',
    'common.below': 'below',
    'common.critical': 'Critical',
    'common.userAgent': 'User Agent',
    'common.before': 'Before',
    'common.after': 'After',
    'common.none': 'None',
    'common.darkMode': 'Dark Mode',
    'common.lightMode': 'Light Mode',
    
    // Requisitions Extended
    'requisitions.manage': 'Manage requisitions and track fulfillment',
    'requisitions.found': 'requisition(s) found',
    'requisitions.allStatus': 'All Status',
    'requisitions.noRequisitions': 'No requisitions found',
    'requisitions.viewing': 'Viewing',
    'requisitions.selectToView': 'Select a requisition to view details',
    'requisitions.requisitionNumber': 'Requisition Number',
    'requisitions.createdAt': 'Created At',
    'requisitions.requiredBy': 'Required By',
    'requisitions.totalItems': 'Total Items',
    'requisitions.totalQuantity': 'Total Quantity',
    'requisitions.reason': 'Reason',
    'requisitions.notes': 'Notes',
    'requisitions.lineItems': 'Line Items',
    'requisitions.itemCode': 'Item Code',
    'requisitions.itemName': 'Item Name',
    'requisitions.quantity': 'Quantity',
    'requisitions.unit': 'Unit',
    'requisitions.warehouse': 'Warehouse',
    'requisitions.items': 'Items',
    'requisitions.requested': 'Requested',
    'requisitions.issued': 'Issued',
    'requisitions.approving': 'Approving...',
    'requisitions.rejecting': 'Rejecting...',
    'requisitions.fulfilling': 'Fulfilling...',
    'requisitions.rejectionReason': 'Rejection reason (optional):',
    'requisitions.departmentLab': 'Department/Lab',
    'requisitions.selectDeptLab': 'Select Department/Lab',
    'requisitions.approvedBy': 'Approved By',
    'requisitions.timeline': 'Timeline',
    'requisitions.created': 'Created',
    'requisitions.createNewRequest': 'Create a new requisition request',
    'requisitions.addItem': 'Add Item',
    'requisitions.creating': 'Creating...',
    'requisitions.confirmFulfillment': 'Confirm fulfillment of this requisition',
    'requisitions.fulfillDescription': 'This will issue the approved quantities for all items in this requisition. Are you sure?',
    'requisitions.itemsToBeIssued': 'Items to be issued',
    'requisitions.confirmFulfill': 'Confirm Fulfill',
    
    // Reports
    'reports.title': 'Reports',
    'reports.shortages': 'Shortages Report',
    'reports.consumption': 'Consumption by Department',
    'reports.noShortages': 'No shortages found',
    
    // Audit Log
    'auditLog.title': 'Audit Log',
    'auditLog.description': 'Track all system activities and changes',
    'auditLog.searchPlaceholder': 'Search logs...',
    'auditLog.activityLog': 'Activity Log',
    'auditLog.timestamp': 'Timestamp',
    'auditLog.actor': 'Actor',
    'auditLog.entity': 'Entity',
    'auditLog.action': 'Action',
    'auditLog.changes': 'Changes',
    'auditLog.viewDetails': 'View Details',
    'auditLog.noLogs': 'No audit logs found',
    
    // Items
    'items.title': 'Items',
    'items.description': 'Manage your inventory items',
    'items.create': 'Create Item',
    'items.searchPlaceholder': 'Search items...',
    'items.itemCode': 'Item Code',
    'items.itemName': 'Item Name',
    'items.category': 'Category',
    'items.unit': 'Unit',
    'items.minStock': 'Min Stock',
    'items.maxStock': 'Max Stock',
    'items.currentStock': 'Current Stock',
    'items.actions': 'Actions',
    'items.noItems': 'No items found',
    'items.editItem': 'Edit Item',
    'items.createItem': 'Create Item',
    'items.deleteConfirm': 'Are you sure you want to delete this item?',
    'items.updateInfo': 'Update item information',
    'items.addNew': 'Add a new item to your inventory',
    'items.selectCategory': 'Select Category',
    'items.saving': 'Saving...',
    'items.code': 'Code',
    'items.name': 'Name',
    
    // Inventory Count
    'inventoryCount.title': 'Inventory Count',
    'inventoryCount.description': 'Manage inventory counting sessions',
    'inventoryCount.startNew': 'Start New Count',
    'inventoryCount.counts': 'Inventory Counts',
    'inventoryCount.countFound': 'count(s) found',
    'inventoryCount.noCounts': 'No inventory counts found',
    'inventoryCount.startFirst': 'Start your first count',
    'inventoryCount.period': 'Period',
    'inventoryCount.warehouse': 'Warehouse',
    'inventoryCount.status': 'Status',
    'inventoryCount.startedAt': 'Started At',
    'inventoryCount.discrepancies': 'Discrepancies',
    'inventoryCount.actions': 'Actions',
    'inventoryCount.open': 'Open',
    'inventoryCount.closed': 'Closed',
    'inventoryCount.closeConfirm': 'Close this count? This will generate ADJUST movements for discrepancies.',
    'inventoryCount.itemCode': 'Item Code',
    'inventoryCount.countedQty': 'Counted Quantity',
    'inventoryCount.systemQty': 'System Quantity',
    'inventoryCount.discrepancy': 'Discrepancy',
    'inventoryCount.downloadTemplate': 'Download Template',
    'inventoryCount.importData': 'Import Data',
    'inventoryCount.validate': 'Validate',
    'inventoryCount.close': 'Close',
    'inventoryCount.back': 'Back',
    'inventoryCount.next': 'Next',
    'inventoryCount.submit': 'Submit',
    
    // Filter Bar
    'filter.warehouse': 'Warehouse',
    'filter.startDate': 'Start Date',
    'filter.endDate': 'End Date',
    'filter.thisMonth': 'This Month',
    
    // Status
    'status.ok': 'OK',
    'status.belowMin': 'Below Min',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.expired': 'Expired',
    'status.expiresIn': 'Expires in',
    'status.days': 'days',
    'status.na': 'N/A',
    
    // Warehouses
    'warehouses.title': 'Warehouses',
    'warehouses.description': 'Manage warehouse locations',
    'warehouses.create': 'Create Warehouse',
    'warehouses.list': 'Warehouses List',
    'warehouses.found': 'warehouse(s) found',
    'warehouses.noWarehouses': 'No warehouses found',
    'warehouses.createFirst': 'Create your first warehouse',
    'warehouses.name': 'Name',
    'warehouses.location': 'Location',
    'warehouses.itemsCount': 'Items Count',
    'warehouses.edit': 'Edit Warehouse',
    'warehouses.createNew': 'Create Warehouse',
    'warehouses.updateInfo': 'Update warehouse information',
    'warehouses.addNew': 'Add a new warehouse location',
    'warehouses.saving': 'Saving...',
    'warehouses.deleteConfirm': 'Are you sure you want to delete this warehouse?',
    
    // Lots
    'lots.title': 'Lots / Batches',
    'lots.description': 'Manage inventory batches and track expiry dates',
    'lots.searchPlaceholder': 'Search batch numbers...',
    'lots.allItems': 'All Items',
    'lots.stockLots': 'Stock Lots',
    'lots.found': 'lot(s) found',
    'lots.noLots': 'No lots found',
    'lots.batchNo': 'Batch No',
    'lots.quantity': 'Quantity',
    'lots.expiryDate': 'Expiry Date',
    
    // Movements
    'movements.title': 'Movements',
    'movements.description': 'Track all inventory movements',
    'movements.new': 'New Movement',
    'movements.searchPlaceholder': 'Search movements...',
    'movements.type': 'Type',
    'movements.allTypes': 'All Types',
    'movements.history': 'Movements History',
    'movements.found': 'movement(s) found',
    'movements.noMovements': 'No movements found',
    'movements.date': 'Date',
    'movements.refNo': 'Ref No',
    'movements.from': 'From',
    'movements.to': 'To',
    'movements.quantity': 'Quantity',
    'movements.actor': 'Actor',
    'movements.recordNew': 'Record a new inventory movement',
    'movements.selectItem': 'Select Item',
    'movements.selectWarehouse': 'Select Warehouse',
    'movements.toWarehouse': 'To Warehouse',
    'movements.fromWarehouse': 'From Warehouse',
    'movements.referenceNo': 'Reference No',
    'movements.autoGenerated': 'Auto-generated if empty',
    'movements.notes': 'Notes',
    'movements.creating': 'Creating...',
    'movements.sourceRequired': 'Please select source warehouse for OUT movement',
    'movements.bothRequired': 'Please select both source and destination warehouses for TRANSFER',
    'movements.destRequired': 'Please select destination warehouse for IN movement',
    
    // Inventory Count Actions
    'inventoryCount.continue': 'Continue',
    'inventoryCount.view': 'View',
    'inventoryCount.selectWarehouse': 'Select Warehouse',
    'inventoryCount.start': 'Start',
    'inventoryCount.starting': 'Starting...',
    'inventoryCount.selectWarehousePeriod': 'Select warehouse and period',
    'inventoryCount.uploadCountData': 'Upload count data',
    'inventoryCount.reviewDiscrepancies': 'Review discrepancies',
    'inventoryCount.generateAdjustments': 'Generate adjustments',
    'inventoryCount.periodPlaceholder': 'e.g., 2024-Q1',
    'inventoryCount.startCount': 'Start Count',
    'inventoryCount.backToList': 'Back to List',
    'inventoryCount.completeProcess': 'Complete the inventory counting process',
    'inventoryCount.importCountData': 'Import Count Data',
    'inventoryCount.enterQuantities': 'Enter counted quantities for each item',
    'inventoryCount.enterQuantitiesDesc': 'Enter counted quantities for each item. You can also download a template CSV.',
    'inventoryCount.validationErrors': 'Validation Errors:',
    'inventoryCount.countData': 'Count Data',
    'inventoryCount.addRow': 'Add Row',
    'inventoryCount.noDataEntered': 'No data entered. Click "Add Row" to start.',
    'inventoryCount.remove': 'Remove',
    'inventoryCount.submitData': 'Submit Data',
    'inventoryCount.submitting': 'Submitting...',
    'inventoryCount.validateDiscrepancies': 'Validate Discrepancies',
    'inventoryCount.reviewDiscrepanciesDesc': 'Review and validate discrepancies before closing the count',
    'inventoryCount.closeCount': 'Close Count',
    'inventoryCount.closing': 'Closing...',
    'inventoryCount.closeCountDesc': 'Close this count and generate ADJUST movements for discrepancies',
    
    // Settings Tabs
    'settings.usersRoles': 'Users & Roles',
    'settings.integrations': 'Integrations',
    'settings.users': 'Users',
    'settings.roles': 'Roles',
    'settings.permissions': 'Permissions',
    'settings.manageUsers': 'Manage system users and their roles',
    'settings.manageRoles': 'Configure role-based access permissions',
    'settings.manageIntegrations': 'Manage external service integrations',
    'settings.emailNotifications': 'Email Notifications',
    'settings.enableEmail': 'Enable email notifications for system events',
    'settings.apiAccess': 'API Access',
    'settings.generateApiKey': 'Generate API key for external integrations',
    'settings.webhooks': 'Webhooks',
    'settings.configureWebhooks': 'Configure webhook endpoints for real-time updates',
    'settings.addUser': 'Add User',
    'settings.editUser': 'Edit User',
    'settings.passwordHint': 'Leave blank to keep current password',
    'settings.permissionMatrix': 'Permission Matrix',
    'settings.viewPermissions': 'View permissions for each role',
    'settings.email': 'Email',
    'common.email': 'Email',
    'common.emailPlaceholder': 'user@example.com',
    'common.firstName': 'First Name',
    'common.lastName': 'Last Name',
    'settings.emailAlerts': 'Send email alerts for low stock and requisitions',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.smsAlerts': 'Send SMS alerts for urgent matters',
    'settings.connected': 'Connected',
    'settings.notConnected': 'Not Connected',
    'settings.configureIntegrations': 'Configure Integrations',
    'settings.permissionManageItems': 'Manage Items',
    'settings.permissionManageWarehouses': 'Manage Warehouses',
    'settings.permissionCreateRequisitions': 'Create Requisitions',
    'settings.permissionApproveRequisitions': 'Approve Requisitions',
    'settings.permissionFulfillRequisitions': 'Fulfill Requisitions',
    'settings.permissionViewReports': 'View Reports',
    'settings.permissionViewAuditLog': 'View Audit Log',
    'settings.permissionManageUsers': 'Manage Users',
    'settings.persianRTL': 'Persian (RTL)',
    'settings.englishLTR': 'English (LTR)',
    
    // Chart Labels
    'chart.in': 'IN',
    'chart.out': 'OUT',
    'chart.net': 'NET',
    'chart.week': 'Week',
    'chart.stockLevel': 'Stock Level',
    'chart.noData': 'No data',
    
    // Movement Types
    'movements.typeIN': 'IN',
    'movements.typeOUT': 'OUT',
    'movements.typeADJUST': 'ADJUST',
    'movements.typeRETURN': 'RETURN',
    'movements.typeTRANSFER': 'TRANSFER',
    
    // Inventory Count Missing
    'inventoryCount.row': 'Row',
    'inventoryCount.itemCodeRequired': 'Item code is required',
    'inventoryCount.quantityCannotBeNegative': 'Quantity cannot be negative',
    'inventoryCount.itemNotFound': 'Item not found: {code}',
    'inventoryCount.delta': 'Delta',
    'inventoryCount.noChange': 'No Change',
    'inventoryCount.noDiscrepancies': 'No discrepancies found',
    'inventoryCount.proceedToClose': 'Proceed to Close',
    'inventoryCount.warningClose': 'Closing this count will generate ADJUST movements for all discrepancies. This action cannot be undone.',
    'inventoryCount.foundDiscrepancies': 'Found {count} discrepancy/discrepancies',
    'inventoryCount.itemCodePlaceholder': 'e.g., CHEM-001',
  },
  fa: {
    // Navigation
    'nav.dashboard': 'داشبورد',
    'nav.inventory': 'موجودی',
    'nav.requisitions': 'درخواست‌ها',
    'nav.count': 'شمارش',
    'nav.reports': 'گزارش‌ها',
    'nav.auditLog': 'لاگ حسابرسی',
    'nav.settings': 'تنظیمات',
    'nav.profile': 'پروفایل',
    'nav.logout': 'خروج',
    
    // Dashboard
    'dashboard.title': 'داشبورد',
    'dashboard.welcome': 'خوش آمدید! اینجا آنچه امروز با موجودی شما اتفاق می‌افتد را می‌بینید.',
    'dashboard.newRequisition': 'درخواست جدید',
    'dashboard.shortages': 'کمبودها',
    'dashboard.pendingRequisitions': 'درخواست‌های در انتظار',
    'dashboard.activeCounts': 'شمارش‌های فعال',
    'dashboard.totalItems': 'کل اقلام',
    'dashboard.lowStock': 'اقلام کم‌موجود',
    'dashboard.vsLastMonth': 'در مقایسه با ماه قبل',
    'dashboard.reviewNow': 'بررسی الان',
    'dashboard.monthlyFlow': 'جریان ماهانه',
    'dashboard.recentMovements': 'حرکات اخیر',
    'dashboard.lowStockAlert': 'هشدار کم‌موجودی',
    'dashboard.noShortages': 'کمبودی شناسایی نشد',
    'dashboard.noPendingRequisitions': 'درخواست در انتظاری وجود ندارد',
    'dashboard.noActiveCounts': 'شمارش فعالی وجود ندارد',
    'dashboard.noLowStock': 'همه اقلام به خوبی موجود هستند',
    'dashboard.noMovements': 'حرکتی وجود ندارد',
    'dashboard.quickActions': 'عملیات سریع',
    'dashboard.quickActionsDesc': 'وظایف و میانبرها',
    'dashboard.createRequisition': 'ایجاد درخواست',
    'dashboard.recordMovement': 'ثبت حرکت',
    'dashboard.startCount': 'شروع شمارش موجودی',
    'dashboard.viewReports': 'مشاهده گزارش‌ها',
    'dashboard.stockTrends': 'روند موجودی',
    'dashboard.weeklyStock': 'سطح موجودی هفتگی',
    'dashboard.noData': 'داده‌ای در دسترس نیست',
    'dashboard.thisMonth': 'این ماه',
    'dashboard.shortage': 'کمبود',
    'dashboard.critical': 'بحرانی',
    
    // Inventory Management
    'inventory.title': 'مدیریت موجودی',
    'inventory.description': 'مدیریت اقلام، انبارها، دسته‌ها و حرکات',
    'inventory.items': 'اقلام',
    'inventory.warehouses': 'انبارها',
    'inventory.warehousesShort': 'انبار',
    'inventory.lots': 'دسته‌ها / بچ‌ها',
    'inventory.lotsShort': 'دسته‌ها',
    'inventory.movements': 'حرکات',
    
    // Requisitions
    'requisitions.title': 'درخواست‌ها',
    'requisitions.new': 'درخواست جدید',
    'requisitions.create': 'ایجاد درخواست',
    'requisitions.approve': 'تایید',
    'requisitions.reject': 'رد',
    'requisitions.fulfill': 'اجرا',
    'requisitions.status': 'وضعیت',
    'requisitions.draft': 'پیش‌نویس',
    'requisitions.pending': 'در انتظار',
    'requisitions.approved': 'تایید شده',
    'requisitions.rejected': 'رد شده',
    'requisitions.fulfilled': 'اجرا شده',
    
    // Settings
    'settings.title': 'تنظیمات',
    'settings.language': 'تغییر زبان',
    'settings.currentLanguage': 'فعلی',
    'settings.switchToEnglish': 'تبدیل به انگلیسی',
    'settings.switchToPersian': 'تبدیل به فارسی',
    'settings.security': 'تنظیمات امنیتی',
    'settings.securityDescription': 'پیکربندی سیاست‌های امنیتی و تنظیمات جلسه',
    'settings.sessionTimeout': 'زمان انقضای جلسه (دقیقه)',
    'settings.passwordPolicy': 'سیاست رمز عبور',
    'settings.minChars': 'حداقل ۸ کاراکتر',
    'settings.requireCase': 'نیاز به حروف بزرگ و کوچک',
    'settings.requireNumbers': 'نیاز به اعداد',
    'settings.saveSecurity': 'ذخیره تنظیمات امنیتی',
    'settings.usersRoles': 'کاربران و نقش‌ها',
    'settings.integrations': 'یکپارچه‌سازی‌ها',
    'settings.users': 'کاربران',
    'settings.roles': 'نقش‌ها',
    'settings.permissions': 'مجوزها',
    'settings.manageUsers': 'مدیریت کاربران سیستم و نقش‌های آن‌ها',
    'settings.manageRoles': 'پیکربندی مجوزهای دسترسی مبتنی بر نقش',
    'settings.manageIntegrations': 'مدیریت یکپارچه‌سازی‌های سرویس خارجی',
    'settings.emailNotifications': 'اعلان‌های ایمیل',
    'settings.enableEmail': 'فعال‌سازی اعلان‌های ایمیل برای رویدادهای سیستم',
    'settings.apiAccess': 'دسترسی API',
    'settings.generateApiKey': 'تولید کلید API برای یکپارچه‌سازی‌های خارجی',
    'settings.webhooks': 'Webhooks',
    'settings.configureWebhooks': 'پیکربندی نقاط پایانی webhook برای به‌روزرسانی‌های بلادرنگ',
    'settings.addUser': 'افزودن کاربر',
    'settings.editUser': 'ویرایش کاربر',
    'settings.passwordHint': 'برای حفظ رمز عبور فعلی خالی بگذارید',
    'settings.permissionMatrix': 'ماتریس مجوزها',
    'settings.viewPermissions': 'مشاهده مجوزها برای هر نقش',
    'settings.emailAlerts': 'ارسال هشدارهای ایمیل برای کم‌موجودی و درخواست‌ها',
    'settings.smsNotifications': 'اعلان‌های پیامک',
    'settings.smsAlerts': 'ارسال هشدارهای پیامک برای مسائل فوری',
    'settings.connected': 'متصل',
    'settings.notConnected': 'غیر متصل',
    'settings.configureIntegrations': 'پیکربندی یکپارچه‌سازی‌ها',
    'settings.persianRTL': 'فارسی (راست به چپ)',
    'settings.englishLTR': 'انگلیسی (چپ به راست)',
    
    // Login
    'login.title': 'اینونترا',
    'login.subtitle': 'اپلیکیشن ردیابی موجودی',
    'login.username': 'نام کاربری',
    'login.password': 'رمز عبور',
    'login.usernamePlaceholder': 'نام کاربری خود را وارد کنید',
    'login.passwordPlaceholder': 'رمز عبور خود را وارد کنید',
    'login.signIn': 'ورود',
    'login.loading': 'در حال بارگذاری...',
    'login.mockMode': 'از هر نام کاربری/رمز عبوری برای ورود استفاده کنید (حالت آزمایشی)',
    
    // Common
    'common.loading': 'در حال بارگذاری...',
    'common.save': 'ذخیره',
    'common.cancel': 'لغو',
    'common.delete': 'حذف',
    'common.edit': 'ویرایش',
    'common.create': 'ایجاد',
    'common.update': 'به‌روزرسانی',
    'common.search': 'جستجو',
    'common.filter': 'فیلتر',
    'common.actions': 'عملیات',
    'common.close': 'بستن',
    'common.confirm': 'تایید',
    'common.yes': 'بله',
    'common.no': 'خیر',
    'common.role': 'نقش',
    'common.admin': 'مدیر',
    'common.storekeeper': 'انباردار',
    'common.requester': 'درخواست‌دهنده',
    'common.auditor': 'حسابرس',
    'common.menu': 'منو',
    'common.all': 'همه',
    'common.select': 'انتخاب',
    'common.view': 'مشاهده',
    'common.details': 'جزئیات',
    'common.noData': 'داده‌ای یافت نشد',
    'common.found': 'یافت شد',
    'common.items': 'اقلام',
    'common.item': 'قلم',
    'common.warehouse': 'انبار',
    'common.allWarehouses': 'همه انبارها',
    'common.category': 'دسته‌بندی',
    'common.allCategories': 'همه دسته‌بندی‌ها',
    'common.startDate': 'تاریخ شروع',
    'common.endDate': 'تاریخ پایان',
    'common.thisMonth': 'این ماه',
    'common.neededBy': 'نیاز تا',
    'common.department': 'بخش',
    'common.manage': 'مدیریت',
    'common.track': 'ردیابی',
    'common.activity': 'فعالیت',
    'common.entity': 'موجودیت',
    'common.allEntities': 'همه موجودیت‌ها',
    'common.allActions': 'همه عملیات',
    'common.currentStock': 'موجودی فعلی',
    'common.minStock': 'حداقل موجودی',
    'common.shortage': 'کمبود',
    'common.consumption': 'مصرف',
    'common.byDepartment': 'بر اساس بخش',
    'common.address': 'آدرس',
    'common.below': 'زیر',
    'common.critical': 'بحرانی',
    'common.userAgent': 'عامل کاربر',
    'common.before': 'قبل',
    'common.after': 'بعد',
    'common.none': 'هیچکدام',
    'common.darkMode': 'حالت تاریک',
    'common.lightMode': 'حالت روشن',
    'common.email': 'ایمیل',
    'common.emailPlaceholder': 'user@example.com',
    'common.firstName': 'نام',
    'common.lastName': 'نام خانوادگی',
    
    // Requisitions Extended
    'requisitions.manage': 'مدیریت درخواست‌ها و ردیابی اجرا',
    'requisitions.found': 'درخواست یافت شد',
    'requisitions.allStatus': 'همه وضعیت‌ها',
    'requisitions.noRequisitions': 'درخواستی یافت نشد',
    'requisitions.viewing': 'مشاهده',
    'requisitions.selectToView': 'یک درخواست انتخاب کنید تا جزئیات را ببینید',
    'requisitions.requisitionNumber': 'شماره درخواست',
    'requisitions.createdAt': 'تاریخ ایجاد',
    'requisitions.requiredBy': 'نیاز تا',
    'requisitions.totalItems': 'کل اقلام',
    'requisitions.totalQuantity': 'کل مقدار',
    'requisitions.reason': 'دلیل',
    'requisitions.notes': 'یادداشت‌ها',
    'requisitions.lineItems': 'اقلام خط',
    'requisitions.itemCode': 'کد قلم',
    'requisitions.itemName': 'نام قلم',
    'requisitions.quantity': 'مقدار',
    'requisitions.unit': 'واحد',
    'requisitions.warehouse': 'انبار',
    'requisitions.items': 'اقلام',
    'requisitions.requested': 'درخواست شده',
    'requisitions.issued': 'صادر شده',
    'requisitions.approving': 'در حال تایید...',
    'requisitions.rejecting': 'در حال رد...',
    'requisitions.fulfilling': 'در حال اجرا...',
    'requisitions.rejectionReason': 'دلیل رد (اختیاری):',
    'requisitions.departmentLab': 'بخش/آزمایشگاه',
    'requisitions.selectDeptLab': 'انتخاب بخش/آزمایشگاه',
    'requisitions.approvedBy': 'تایید شده توسط',
    'requisitions.timeline': 'زمان‌بندی',
    'requisitions.created': 'ایجاد شده',
    'requisitions.createNewRequest': 'ایجاد درخواست جدید',
    'requisitions.addItem': 'افزودن قلم',
    'requisitions.creating': 'در حال ایجاد...',
    'requisitions.confirmFulfillment': 'تایید اجرای این درخواست',
    'requisitions.fulfillDescription': 'این کار مقادیر تایید شده برای تمام اقلام این درخواست را صادر می‌کند. آیا مطمئن هستید؟',
    'requisitions.itemsToBeIssued': 'اقلامی که باید صادر شوند',
    'requisitions.confirmFulfill': 'تایید اجرا',
    
    // Reports
    'reports.title': 'گزارش‌ها',
    'reports.shortages': 'گزارش کمبودها',
    'reports.consumption': 'مصرف بر اساس بخش',
    'reports.noShortages': 'کمبودی یافت نشد',
    
    // Audit Log
    'auditLog.title': 'لاگ حسابرسی',
    'auditLog.description': 'ردیابی تمام فعالیت‌ها و تغییرات سیستم',
    'auditLog.searchPlaceholder': 'جستجوی لاگ‌ها...',
    'auditLog.activityLog': 'لاگ فعالیت',
    'auditLog.timestamp': 'زمان',
    'auditLog.actor': 'فعال کننده',
    'auditLog.entity': 'موجودیت',
    'auditLog.action': 'عملیات',
    'auditLog.changes': 'تغییرات',
    'auditLog.viewDetails': 'مشاهده جزئیات',
    'auditLog.noLogs': 'لاگ حسابرسی یافت نشد',
    
    // Items
    'items.title': 'اقلام',
    'items.description': 'مدیریت اقلام موجودی',
    'items.create': 'ایجاد قلم',
    'items.searchPlaceholder': 'جستجوی اقلام...',
    'items.itemCode': 'کد قلم',
    'items.itemName': 'نام قلم',
    'items.category': 'دسته‌بندی',
    'items.unit': 'واحد',
    'items.minStock': 'حداقل موجودی',
    'items.maxStock': 'حداکثر موجودی',
    'items.currentStock': 'موجودی فعلی',
    'items.actions': 'عملیات',
    'items.noItems': 'اقلامی یافت نشد',
    'items.editItem': 'ویرایش قلم',
    'items.createItem': 'ایجاد قلم',
    'items.deleteConfirm': 'آیا مطمئن هستید که می‌خواهید این قلم را حذف کنید؟',
    'items.updateInfo': 'به‌روزرسانی اطلاعات قلم',
    'items.addNew': 'افزودن قلم جدید به موجودی',
    'items.selectCategory': 'انتخاب دسته‌بندی',
    'items.saving': 'در حال ذخیره...',
    'items.code': 'کد',
    'items.name': 'نام',
    
    // Warehouses
    'warehouses.title': 'انبارها',
    'warehouses.description': 'مدیریت مکان‌های انبار',
    'warehouses.create': 'ایجاد انبار',
    'warehouses.list': 'لیست انبارها',
    'warehouses.found': 'انبار یافت شد',
    'warehouses.noWarehouses': 'انباری یافت نشد',
    'warehouses.createFirst': 'اولین انبار خود را ایجاد کنید',
    'warehouses.name': 'نام',
    'warehouses.location': 'مکان',
    'warehouses.itemsCount': 'تعداد اقلام',
    'warehouses.edit': 'ویرایش انبار',
    'warehouses.createNew': 'ایجاد انبار',
    'warehouses.updateInfo': 'به‌روزرسانی اطلاعات انبار',
    'warehouses.addNew': 'افزودن مکان انبار جدید',
    'warehouses.saving': 'در حال ذخیره...',
    'warehouses.deleteConfirm': 'آیا مطمئن هستید که می‌خواهید این انبار را حذف کنید؟',
    
    // Lots
    'lots.title': 'دسته‌ها / بچ‌ها',
    'lots.description': 'مدیریت دسته‌های موجودی و ردیابی تاریخ انقضا',
    'lots.searchPlaceholder': 'جستجوی شماره دسته...',
    'lots.allItems': 'همه اقلام',
    'lots.stockLots': 'دسته‌های موجودی',
    'lots.found': 'دسته یافت شد',
    'lots.noLots': 'دسته‌ای یافت نشد',
    'lots.batchNo': 'شماره دسته',
    'lots.quantity': 'مقدار',
    'lots.expiryDate': 'تاریخ انقضا',
    
    // Movements
    'movements.title': 'حرکات',
    'movements.description': 'ردیابی تمام حرکات موجودی',
    'movements.new': 'حرکت جدید',
    'movements.searchPlaceholder': 'جستجوی حرکات...',
    'movements.type': 'نوع',
    'movements.allTypes': 'همه انواع',
    'movements.history': 'تاریخچه حرکات',
    'movements.found': 'حرکت یافت شد',
    'movements.noMovements': 'حرکتی یافت نشد',
    'movements.date': 'تاریخ',
    'movements.refNo': 'شماره مرجع',
    'movements.from': 'از',
    'movements.to': 'به',
    'movements.quantity': 'مقدار',
    'movements.actor': 'فعال کننده',
    'movements.recordNew': 'ثبت حرکت جدید موجودی',
    'movements.selectItem': 'انتخاب قلم',
    'movements.selectWarehouse': 'انتخاب انبار',
    'movements.toWarehouse': 'به انبار',
    'movements.fromWarehouse': 'از انبار',
    'movements.referenceNo': 'شماره مرجع',
    'movements.autoGenerated': 'تولید خودکار در صورت خالی بودن',
    'movements.notes': 'یادداشت‌ها',
    'movements.creating': 'در حال ایجاد...',
    'movements.sourceRequired': 'لطفاً انبار مبدا را برای حرکت خروج انتخاب کنید',
    'movements.bothRequired': 'لطفاً هر دو انبار مبدا و مقصد را برای انتقال انتخاب کنید',
    'movements.destRequired': 'لطفاً انبار مقصد را برای حرکت ورود انتخاب کنید',
    
    // Inventory Count
    'inventoryCount.title': 'شمارش موجودی',
    'inventoryCount.description': 'مدیریت جلسات شمارش موجودی',
    'inventoryCount.startNew': 'شروع شمارش جدید',
    'inventoryCount.counts': 'شمارش‌های موجودی',
    'inventoryCount.countFound': 'شمارش یافت شد',
    'inventoryCount.noCounts': 'شمارش موجودی یافت نشد',
    'inventoryCount.startFirst': 'اولین شمارش خود را شروع کنید',
    'inventoryCount.period': 'دوره',
    'inventoryCount.warehouse': 'انبار',
    'inventoryCount.status': 'وضعیت',
    'inventoryCount.startedAt': 'شروع شده در',
    'inventoryCount.discrepancies': 'اختلافات',
    'inventoryCount.actions': 'عملیات',
    'inventoryCount.open': 'باز',
    'inventoryCount.closed': 'بسته',
    'inventoryCount.closeConfirm': 'این شمارش را ببندید؟ این کار حرکات ADJUST برای اختلافات ایجاد می‌کند.',
    'inventoryCount.itemCode': 'کد قلم',
    'inventoryCount.countedQty': 'مقدار شمارش شده',
    'inventoryCount.systemQty': 'مقدار سیستم',
    'inventoryCount.discrepancy': 'اختلاف',
    'inventoryCount.downloadTemplate': 'دانلود الگو',
    'inventoryCount.importData': 'وارد کردن داده',
    'inventoryCount.validate': 'اعتبارسنجی',
    'inventoryCount.close': 'بستن',
    'inventoryCount.back': 'بازگشت',
    'inventoryCount.next': 'بعدی',
    'inventoryCount.submit': 'ارسال',
    
    // Filter Bar
    'filter.warehouse': 'انبار',
    'filter.startDate': 'تاریخ شروع',
    'filter.endDate': 'تاریخ پایان',
    'filter.thisMonth': 'این ماه',
    
    // Status
    'status.ok': 'خوب',
    'status.belowMin': 'زیر حداقل',
    'status.active': 'فعال',
    'status.inactive': 'غیرفعال',
    'status.expired': 'منقضی شده',
    'status.expiresIn': 'منقضی می‌شود در',
    'status.days': 'روز',
    'status.na': 'نامشخص',
    
    // Settings Permissions
    'settings.permissionManageItems': 'مدیریت اقلام',
    'settings.permissionManageWarehouses': 'مدیریت انبارها',
    'settings.permissionCreateRequisitions': 'ایجاد درخواست‌ها',
    'settings.permissionApproveRequisitions': 'تایید درخواست‌ها',
    'settings.permissionFulfillRequisitions': 'اجرای درخواست‌ها',
    'settings.permissionViewReports': 'مشاهده گزارشات',
    'settings.permissionViewAuditLog': 'مشاهده لاگ حسابرسی',
    'settings.permissionManageUsers': 'مدیریت کاربران',
    
    // Chart Labels
    'chart.in': 'ورود',
    'chart.out': 'خروج',
    'chart.net': 'خالص',
    'chart.week': 'هفته',
    'chart.stockLevel': 'سطح موجودی',
    'chart.noData': 'داده‌ای وجود ندارد',
    
    // Movement Types
    'movements.typeIN': 'ورود',
    'movements.typeOUT': 'خروج',
    'movements.typeADJUST': 'تنظیم',
    'movements.typeRETURN': 'بازگشت',
    'movements.typeTRANSFER': 'انتقال',
    
    // Inventory Count Missing
    'inventoryCount.row': 'ردیف',
    'inventoryCount.itemCodeRequired': 'کد قلم الزامی است',
    'inventoryCount.quantityCannotBeNegative': 'مقدار نمی‌تواند منفی باشد',
    'inventoryCount.itemNotFound': 'قلم یافت نشد: {code}',
    'inventoryCount.delta': 'اختلاف',
    'inventoryCount.noChange': 'بدون تغییر',
    'inventoryCount.noDiscrepancies': 'اختلافی یافت نشد',
    'inventoryCount.proceedToClose': 'ادامه به بستن',
    'inventoryCount.warningClose': 'بستن این شمارش حرکات ADJUST برای تمام اختلافات ایجاد می‌کند. این عمل قابل بازگشت نیست.',
    'inventoryCount.foundDiscrepancies': '{count} اختلاف یافت شد',
    'inventoryCount.itemCodePlaceholder': 'مثال: CHEM-001',
    
    // Inventory Count Extended
    'inventoryCount.importCountData': 'وارد کردن داده شمارش',
    'inventoryCount.enterQuantities': 'وارد کردن مقادیر شمارش شده برای هر قلم',
    'inventoryCount.enterQuantitiesDesc': 'مقادیر شمارش شده برای هر قلم را وارد کنید. همچنین می‌توانید الگوی CSV را دانلود کنید.',
    'inventoryCount.validationErrors': 'خطاهای اعتبارسنجی:',
    'inventoryCount.countData': 'داده شمارش',
    'inventoryCount.addRow': 'افزودن ردیف',
    'inventoryCount.noDataEntered': 'داده‌ای وارد نشده است. برای شروع روی "افزودن ردیف" کلیک کنید.',
    'inventoryCount.remove': 'حذف',
    'inventoryCount.submitData': 'ارسال داده',
    'inventoryCount.submitting': 'در حال ارسال...',
    'inventoryCount.validateDiscrepancies': 'اعتبارسنجی اختلافات',
    'inventoryCount.reviewDiscrepanciesDesc': 'بررسی و اعتبارسنجی اختلافات قبل از بستن شمارش',
    'inventoryCount.closeCount': 'بستن شمارش',
    'inventoryCount.closing': 'در حال بستن...',
    'inventoryCount.closeCountDesc': 'بستن این شمارش و ایجاد حرکات ADJUST برای اختلافات',
    'inventoryCount.start': 'شروع',
    'inventoryCount.startCount': 'شروع شمارش',
    'inventoryCount.starting': 'در حال شروع...',
    'inventoryCount.continue': 'ادامه',
    'inventoryCount.view': 'مشاهده',
    'inventoryCount.selectWarehousePeriod': 'انتخاب انبار و دوره',
    'inventoryCount.uploadCountData': 'آپلود داده شمارش',
    'inventoryCount.reviewDiscrepancies': 'بررسی اختلافات',
    'inventoryCount.generateAdjustments': 'ایجاد تنظیمات',
    'inventoryCount.periodPlaceholder': 'مثال: 2024-Q1',
    'inventoryCount.backToList': 'بازگشت به لیست',
    'inventoryCount.completeProcess': 'تکمیل فرآیند شمارش موجودی',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // خواندن از localStorage
    const saved = localStorage.getItem('language') as Language;
    return saved || 'en';
  });

  const isRTL = language === 'fa';

  useEffect(() => {
    // ذخیره در localStorage
    localStorage.setItem('language', language);
    
    // اضافه/حذف کلاس RTL از body
    if (isRTL) {
      document.documentElement.setAttribute('dir', 'rtl');
      document.documentElement.setAttribute('lang', 'fa');
      document.body.classList.add('rtl');
    } else {
      document.documentElement.setAttribute('dir', 'ltr');
      document.documentElement.setAttribute('lang', 'en');
      document.body.classList.remove('rtl');
    }
  }, [language, isRTL]);

  const toggleLanguage = () => {
    setLanguageState((prev) => (prev === 'en' ? 'fa' : 'en'));
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        isRTL,
        toggleLanguage,
        setLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};



